# Generated by Django 2.1.5 on 2019-01-24 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('read_count', '0002_readderail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReadDerail',
            new_name='ReadDetail',
        ),
    ]
